spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related to Production APIs "
  contactDetails:
    name: "Lalit - QA Lead"
    email: "lalit@eazybank.com"
  onCallSupport:
    - (888) 555-1234
    - (888) 523-1345