spring:
  config:
    activate:
        on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related to QA APIs "
  contactDetails:
    name: "Gaurav - QA Lead"
    email: "gaurav@eazybank.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345